# Generated by Django 4.2.5 on 2023-09-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mojoodi',
            field=models.IntegerField(default=0),
        ),
    ]
