# Generated by Django 4.2.5 on 2023-09-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_product_offer_alter_future_img_alter_image_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deepcat',
            name='catname',
        ),
        migrations.AddField(
            model_name='category',
            name='depp_cat',
            field=models.ManyToManyField(to='root.deepcat'),
        ),
    ]
