# Generated by Django 4.2.5 on 2023-10-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_alter_contact_facebook_alter_contact_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(default='image/default/default.png', upload_to='image/brands'),
        ),
    ]
