# Generated by Django 4.2.5 on 2023-10-02 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_alter_brand_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mojoodi',
        ),
        migrations.RemoveField(
            model_name='product',
            name='offer',
        ),
    ]
