# Generated by Django 4.2.5 on 2023-09-29 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_rename_depp_cat_category_deep_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='call2',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email2',
        ),
    ]
