# Generated by Django 4.2.5 on 2023-10-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_remove_product_image2_remove_product_image3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
