# Generated by Django 4.2.5 on 2023-10-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0008_contect_f'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contect_f',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
