# Generated by Django 4.2.5 on 2023-10-03 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0009_alter_contect_f_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contect_f',
            options={},
        ),
        migrations.RemoveField(
            model_name='contect_f',
            name='created_date',
        ),
    ]
